name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: WyriHaximus/github-action-helm3@v2
    - name: Build the site in the jekyll/builder container   
      run: |
         helm repo add --username slamani mizen-repository https://1751181b7343308cd891dfbc33b75a3e0c9f7a18@raw.githubusercontent.com/slamani/helm-chart/master/infra-helm-chart


