name: Jekyll site CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Helm
      run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash      

    - name: Build the site in the jekyll/builder container
      run: ${{ secrets.REPO }}
        
      


