name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    
    steps:
    - name: Build the site in the jekyll/builder container   
      run: helm repo add mizen-re  https://c662135fa7a26acd4fac40e44ee8e67b6d30a1ae@raw.githubusercontent.com/slamani/helm-chart/master/infra-helm-chart --username slamani --password password

      


