name: Jekyll site CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Helm
      run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash      

    - name: Add repo1
      run: |-
        helm repo add mizen-qaulif  https://${{ secrets.TOKEN }}@raw.githubusercontent.com/slamani/helm-chart/master/infra-helm-chart
        helm repo update  
        helm repo add mizen  https://${{ secrets.TOKEN2 }}@raw.githubusercontent.com/Mizenek/helm-registry/master/infra-helm-chart
        helm repo update  

